version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 0102
      MYSQL_DATABASE: flights
      PORT: 3000
    volumes:
      - .:/usr/src/app 
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0102
      MYSQL_DATABASE: flights
    volumes:
      - db_data:/var/lib/mysql 

volumes:
  db_data:
